jwt:
  secret: '{wow-8786eh5774%$#@JHg55676jdk}_-%^%hdpiBTFTFTedieGRDiode524326@#$%hgt%ded#@FCg76HAGFISH'


server:
  port: 8036


spring:
  datasource:
    url: jdbc:mysql://localhost/dbgestioneau
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


